components_manager:
  task_processors:                  # Task processor is an executor for coroutine tasks

    main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
      worker_threads: 4         # Process tasks in 4 threads.

    fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
      worker_threads: 2
    man-task-processor:
      worker_threads: 1

  default_task_processor: main-task-processor

  components:                       # Configuring components that were registered via component_list
    server:
      listener:                 # configuring the main listening socket...
        port: 8080            # ...to listen on this port and...
        task_processor: main-task-processor    # ...process incoming requests on this task processor.
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: info
          overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

    # Dynamic config options. Cache is disabled, updates are disabled.
    dynamic-config:
      # For most of userver dynamic configs, defaults are used, some are overridden here.
      # See userver "dynamic config" docs for what configs exist.
      defaults:
        HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

    testsuite-support: {}

    dns-client:
      fs-task-processor: fs-task-processor

    http-client:
      fs-task-processor: fs-task-processor
      dns_resolver: getaddrinfo

    default-secdist-provider: # Component that loads configuration of hosts and passwords
      config: ./secure_data.json  # Values are supposed to be stored in this file
      missing-ok: false                            # ... but if the file is missing it is still ok

    rabbitmq:
      use_secure_connection: false
    mongo:
      dbconnection: mongodb://user:admin@mongodb_1:27017,mongodb_2:27017,mongodb_3:27017/database?replicaSet=rs1
      dns_resolver: getaddrinfo


    storage-service:

    consumer-service:
      queue_add: add
      queue_add_exchange: add-exchange
      queue_result: result
      queue_cancel_exchange: cancel-exchange

    tests-control:
      load-enabled: true
      path: /tests/{action}
      method: POST
      task_processor: main-task-processor
    handler-ping:
      path: /ping
      method: GET
      task_processor: main-task-processor
      throttling_enabled: false
      url_trailing_slash: strict-match

    #handler-hello:                    # Finally! Our handler.
    #    path: /hello                  # Registering handler by URL '/hello'.
    #    method: GET,POST              # It will only reply to GET (HEAD) and POST requests.
    #    task_processor: main-task-processor  # Run it on CPU bound task processor
    handler-manger-solve:
      path: /task/solve
      method: POST
      task_processor: main-task-processor
    handler-manger-status:
      path: /task/status
      method: GET
      task_processor: main-task-processor
